PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select (count(?resource) as ?matches) 
where { 
    ?resource roud-oeuvres:periodicalArticleIsInPages ?pages .
    ?pages knora-base:valueHasString ?pagesString .
    filter(regex(?pagesString, "p. ([\\d^\\d]+)"))
}
