#
# extract the admin data
#
PREFIX knora-admin: <http://www.knora.org/ontology/knora-admin#> 
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#> 

# use construct if you want to export as turtle or trig
construct { 
    ?s ?p ?o .
    ?project ?pp ?po .
}
FROM <http://www.knora.org/data/admin>
FROM <http://www.ontotext.com/explicit>
WHERE
{
    bind(<http://rdfh.ch/projects/0112> as ?project)
    {
        # project definition
        ?project ?pp ?po
    }
    UNION
    {
        # rest
        ?s ?p ?o .
        ?s knora-admin:isInProject ?project
    }
}
