PREFIX knora-admin: <http://www.knora.org/ontology/knora-admin#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>

select 
  ?s ?p ?o
where {
  ?s ?p ?o .
  ?s a knora-admin:User .
}
#limit 50
