PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>  

SELECT 
    distinct
    ?ontologyGraph 
    ?ontologyIri 
    #?project
    #distinct ?label
WHERE {     
    GRAPH ?ontologyGraph {
        ?ontologyIri rdf:type owl:Ontology .
        #             knora-base:attachedToProject ?project .

        #?ontologyIri rdfs:label ?label .
        #FILTER (langMatches(lang(?label), "en")) .
    }
}
